### PR TITLE
research/fragattack: implement --pre-test-delay

### PR DESCRIPTION
**Pull request by angeloc**
Adding --pre-test-delay **parameter**

### CODE REVIEW

**Comment by vanhoefm** [comment]
The delay was implemented in `handle_authenticated` in the following line:

	self.time_connected = time.time() + self.options.connected_delay

This delay should happen after completing the 4-way handshake.

The delay that you seem to be adding is done after getting an IP address. I suppose this difference was important in your case. Can you confirm that a delay after getting the IP address was important? We can add a separate parameter for that.

**Comment by panicking** [comment]
Correct, if we don't have the delay the ping packet in receive interface is dropped. We will check it

**Comment by vanhoefm** [comment]
Thanks for the update, will try to find time to check this.

**Comment by vanhoefm** [comment]
Looks good. I've tweaked the code and pushed those changes (it's the first time I edited a pull request so hopefully that went well). If possible, can you confirm that the updated code works for you? Then I'll merge these changes.

**Comment by angeloc** [comment]
Looks good to me!

**Pull request merged**
